pipeline {

    agent {
        docker {
            image 'jenkins-python-agent:latest'
            args '-u root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }


    environment {
        IMAGE_NAME = "teju96/capstone-project"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }


    stages {


        stage('Checkout') {
            steps {
                checkout scm
            }
        }


        stage('Install Dependencies') {
            steps {
                dir('Capstone Project/app') {
                    sh '''
                    pip install -r requirements.txt
                    '''
                }
            }
        }


        stage('SonarQube Scan') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh '''
                    sonar-scanner \
                    -Dsonar.projectKey=capstone-project \
                    -Dsonar.sources="Capstone Project/app" \
                    -Dsonar.python.version=3.14
                    '''
                }
            }
        }


        stage('Build Docker Image') {
            steps {
                dir('Capstone Project/app') {
                    sh '''
                    docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
                    '''
                }
            }
        }


        stage('Push Docker Image') {
            steps {

                withCredentials([usernamePassword(
                    credentialsId: 'docker-cred',
                    usernameVariable: 'USERNAME',
                    passwordVariable: 'PASSWORD'
                )]) {

                    sh '''
                    echo $PASSWORD | docker login -u $USERNAME --password-stdin

                    docker push ${IMAGE_NAME}:${IMAGE_TAG}

                    docker logout
                    '''
                }
            }
        }


        stage('Update Deployment') {
            steps {
                sh '''
                sed -i "s|image:.*|image: ${IMAGE_NAME}:${IMAGE_TAG}|" "Capstone Project/K8s/deployment.yaml"

                echo "Updated deployment file:"
                cat "Capstone Project/K8s/deployment.yaml"
                '''
            }
        }

    }


    post {

        success {
            echo "Pipeline completed successfully!"
        }


        failure {
            echo "Pipeline failed! Please check logs."
        }


        always {
            cleanWs()
        }

    }

}
