pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Maven') {
            steps {
                dir('CI-CD/spring-boot-app') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('CI-CD/spring-boot-app') {
                    sh 'docker build -t cicd-pipeline:v1 .'
                }
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker rm -f app || true'
                sh 'docker run -d --name app -p 8080:8080 cicd-pipeline:v1'
            }
        }
    }

    post {
        success {
            echo '✅ Pipeline SUCCESS'
        }
        failure {
            echo '❌ Pipeline FAILED'
        }
    }
}
