pipeline {
    agent {
        docker {
            image 'abhishekf5/maven-abhishek-docker-agent:v1'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        SONAR_URL = "http://<YOUR-SONARQUBE-IP>:9000"
        DOCKER_IMAGE = "<YOUR-DOCKERHUB-USERNAME>/spring-boot-demo:${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Tejashwini-Javejar/orn-ai-devops-assessment.git'
            }
        }

        stage('Build and Test') {
            steps {
                sh '''
                cd "CI-CD /spring-boot-app/src-main"
                mvn clean package
                '''
            }
        }

        stage('Static Code Analysis') {
            steps {
                withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
                    sh '''
                    cd "CI-CD /spring-boot-app/src-main"
                    mvn sonar:sonar \
                      -Dsonar.login=$SONAR_AUTH_TOKEN \
                      -Dsonar.host.url=$SONAR_URL
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                cd "CI-CD /spring-boot-app/src-main"
                docker build -t $DOCKER_IMAGE .
                '''
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-cred') {
                        docker.image(DOCKER_IMAGE).push()
                    }
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline execution completed."
        }

        success {
            echo "Build, SonarQube analysis, and Docker image push completed successfully."
        }

        failure {
            echo "Pipeline failed. Check the Jenkins console output for details."
        }
    }
}
