pipeline {
  agent any

  environment {
    DOCKER_IMAGE = "your-dockerhub-username/spring-boot-app:${BUILD_NUMBER}"
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/Tejashwini-Javejar/orn-ai-devops-assessment.git'
      }
    }

    stage('Build') {
      steps {
        sh 'cd CI-CD/spring-boot-app/src-main && mvn clean package'
      }
    }

    stage('Docker Build') {
      steps {
        sh '''
          cd CI-CD/spring-boot-app/src-main
          docker build -t $DOCKER_IMAGE .
        '''
      }
    }

    stage('Docker Push') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'docker-cred', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
          sh '''
            echo $PASS | docker login -u $USER --password-stdin
            docker push $DOCKER_IMAGE
          '''
        }
      }
    }
  }
}
